### ISSUE TITLE
1.21 Return the Stars [Solve]

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Crital#1]
Is the star removal necessary?

**Comment by MasterZeeVII** [comment]
wdym? Does it change from 4 to 2 or increase? It just displays a tier of items, like cosmetics.
or did you want to disable it?

**Comment by MrSypz** [comment]
or like disable it?

**Comment by makumaku1974** [comment]
no... The previous version had like stars in it. Then after downloading the updated version the stars are kinda gone. It just became borders.

**Comment by makumaku1974** [comment]
I just found it out that you can also keep the jumpcrit... Is there a difference with the without jumping and jump crit?

**Comment by MasterZeeVII** [comment]
Q1 : no... The previous version had like stars in it. Then after downloading the updated version the stars are kinda gone. It just became borders.
A:Image pls maybe I can know how it look like, PS: it have a resource build in it like tieredz style

Q2: I just found it out that you can also keep the jumpcrit... Is there a difference with the without jumping and jump crit?
A:Jump crit use vanilla damage * 1.5 and when newcrit system active it'll use crit damage instead of vanilla * X.X value

And did you use anymod that change the boarder renderer? cuz I didn't change anything about the star?
![image](https://github.com/MrSypz/Crital/assets/123331225/f8af7e14-ebb7-4c7a-940b-0a76861d2ecd)
in 0.6.0 I change the boarder style into star and roman number to point a tier and color on the boarder thing

**Comment by makumaku1974** [comment]
Let me check again. with screenshots

**Comment by makumaku1974** [comment]
See? No Stars and Roman Numerals like you have.

![2024-06-22_01 08 24](https://github.com/MrSypz/Crital/assets/129804277/522264dd-f31f-475e-b70d-f53927c69bf9)
![2024-06-22_01 08 27](https://github.com/MrSypz/Crital/assets/129804277/74d04205-b2bd-4bae-a37f-3eb92f0410ae)
![2024-06-22_01 16 50](https://github.com/MrSypz/Crital/assets/129804277/ac167b62-ce93-40e1-8d12-85c7684f82f7)
![2024-06-22_01 08 21](https://github.com/MrSypz/Crital/assets/129804277/36e4d261-df22-48aa-a828-90e5c7ecb1fc)
![2024-06-22_01 08 23](https://github.com/MrSypz/Crital/assets/129804277/68f6e9bc-c126-47ac-9b97-f3027500bc4a)

**Comment by MasterZeeVII** [comment]
Bro u use resources pack that i build in disable it first 💀
![image](https://github.com/MrSypz/Crital/assets/123331225/12d3b914-360f-444b-8714-00676923452b)
Deselect this one

**Comment by makumaku1974** [comment]
Ahh so that's why my bad...

**Comment by MasterZeeVII** [comment]
bruh not only you I have been the same when rewrite it lmao

**Comment by makumaku1974** [comment]
actually, why not mix both they blend well... It even looks like Stardew Valley lol

**Comment by MasterZeeVII** [comment]
Interesting I'll keep your idea to next update
